### ISSUE TITLE
The ATerm Library doesn't compile with Visual C++ 8.1

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#234]
*Issue migrated from trac ticket # 231*

**component:** ATerm Library | **priority:** major | **resolution:** fixed

#### 2007-08-13 09:56:05: @wiegerw created the issue

___
The ATerm Library doesn't compile with Visual C++ 8.1:

D:\mcrl2\3rd-party\aterm\source\gc.c(302) : error C2036: 'void *' : unknown size
D:\mcrl2\3rd-party\aterm\source\gc.c(311) : warning C4018: '<' : signed/unsigned mismatch
D:\mcrl2\3rd-party\aterm\source\gc.c(420) : error C2036: 'void *' : unknown size
