### ISSUE TITLE
Rev 9727 does not compile on Mac OS X 10.6

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#854]
*Issue migrated from trac ticket # 851*

**component:** General | **priority:** critical | **resolution:** fixed

#### 2011-10-11 14:27:34: j.ketema@ewi.utwente.nl created the issue

___
When compiling the latest revision on Max OS X 10.6 using XCode 4.0.2, make bails out with the following error:

```
...
[ 33%] Building C object libraries/core/CMakeFiles/mcrl2_syntax.dir/source/mcrl2_syntax.c.o
Linking C shared library libmcrl2_syntax.dylib
Undefined symbols for architecture x86_64:
  "_dup_str", referenced from:
      _d_speculative_reduction_code_163_362_mcrl2 in mcrl2_syntax.c.o
  "_d_free", referenced from:
      _d_speculative_reduction_code_163_362_mcrl2 in mcrl2_syntax.c.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[r2](../commit/480c7c610): *** [libraries/core/libmcrl2_syntax.dylib] Error 1
make[r1](../commit/27180ff2e): *** [libraries/core/CMakeFiles/mcrl2_syntax.dir/all] Error 2
make: *** [all] Error 2
```
